[package]
name = "rust-tokio"
version = "0.1.0"
authors = ["yancy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { git = "https://github.com/tokio-rs/tokio", features = ["full"] }
